# Languages

[en]
  languageCode = "en-us"
  contentDir = "content/en"

[zh]
  languageCode = "zh-Hans"
  contentDir = "content/zh"
  title = "魏晓宇"
  [zh.params]
    description = "魏晓宇的个人主页"
  [[zh.menu.main]]
    name = "关于我"
    url = "#about"
    weight = 1
